### ISSUE TITLE
todo list

### ISSUE THREAD

**Issue by azazellochg** [azazellochg/MDCatch#2]
- [x] Get detector, beam tilt, vpp from SerialEM - add "AddToNextFrameStackMdoc key value" before R in SerialEM script
- [x] Validation of self.path: check if Images-DicsX folder exists
- [x] Fix file path for relion? Where do we launch this? Probably in the folder where Schedules template folder is.
