### ISSUE TITLE
next todo list

### ISSUE THREAD

**Issue by azazellochg** [azazellochg/MDCatch#30]
- [x] add 3 options: cryolo / topaz or logpicker for picking. Logpicker requires ptcl size. Add corresponding schedules
- [x] add box sizes back as an option?
- [ ] count new movies, if not changed after 2h, stop preprocess
- [x] keep overwriting the first cl2d job until 20k (?) ptcls is reached

**Comment by azazellochg** [comment]
watch mode need to be adapted to new picker options..
