### ISSUE TITLE
to-do list 13/09/2019

### ISSUE THREAD

**Issue by azazellochg** [azazellochg/MDCatch#8]
- [x] user should choose relion project folder, suggest cwd as default
- [x] set relative movie path, create a link from full path to epu session folder
- [x] check relion_it.py code to get optimal box sizes
- [x] more params should be editable
- [x] do not show magnification
- [x] two checkboxes: stop after CTF or do class2D
- [ ] add more prots to scipion template: picking, extraction, cl2d
